### ISSUE TITLE
Unable to fetch movies

### ISSUE THREAD

**Issue by velodromen** [dylandoamaral/trakt-integration#113]
I currently have my tv shows setup and it's working great! I now thought I would set up a movie card as well but I can't get the sensor to work. It is available but it never returns anything? I would like to monitor every new movie released (i currently don't have a watch list/anticipated list and would like to avoid using these). What am I doing wrong?

Code in configuration.yaml:

```
trakt_tv:
  language: en
  timezone: Europe/Stockholm # Prefered timezone
  sensors:
    upcoming:
      show:
        days_to_fetch: 45 # How many days in the future you want to fetch
        max_medias: 5 # How many medias you want to fetch
    all_upcoming:
      movie:
        days_to_fetch: 45
        max_medias: 5

```
