### ISSUE TITLE
I can get movies to work by not TV

### ISSUE THREAD

**Issue by reffr** [dylandoamaral/trakt-integration#13]
Love this integration. I'm not sure what I'm doing wrong. I can get movies to create a sensor and show up. I cannot get the TV function to work. It will not add the TV sensors. Attached my configuration.yaml below. Any help would be greatly appreciated. My apologies if I missed something obvious

```
trakt_tv:
  language: en
  sensors:
    upcoming:
      show:
        days_to_fetch: 90
        max_medias: 9
      new_show:
        days_to_fetch: 90
        max_medias: 9
      premiere:
        days_to_fetch: 90
        max_medias: 9
      movie:
        days_to_fetch: 180
        max_medias: 9
```
