### ISSUE TITLE
Make recommandation sensors compatible with upcoming-media-card

### ISSUE THREAD

**Issue by thomasgermain** [dylandoamaral/trakt-integration#32]
Hello,

I just give a try to the integration; It works quite well, but I found out that some sensors (see below) are not compatible with  upcoming-media-card, their doc says:
> The first item in your JSON must contain these keys to set your defaults: title_default, line1_default, line2_default, line3_default, line4_default, and icon. The default text contents are set exactly like the card's text content config and use the same keywords. The default icon takes an mdi icon mdi:arrow-down.

Here is my integration config

```yaml
trakt_tv:
  language: fr
  sensors:
    upcoming:
      show:
        days_to_fetch: 90
        max_medias: 5
      new_show:
        days_to_fetch: 90
        max_medias: 5
      premiere:
        days_to_fetch: 90
        max_medias: 5
      movie:
        days_to_fetch: 90
        max_medias: 10
    recommendation:
      show:
        max_medias: 3
      movie:
        max_medias: 10
```

It produces compatible sensors (upcoming sensors)
- sensor.trakt_upcoming_movies
- sensor.trakt_upcoming_premieres
- sensor.trakt_upcoming_new_shows

Here is an example of attributes:
```yaml
data: 
- title_default: $title
  line1_default: $episode
  line2_default: $release
  line3_default: $rating - $runtime
  line4_default: $number - $studio
  icon: mdi:arrow-down-bold
- title: Stranger Things
  poster: https://image.tmdb.org/t/p/w500/bR6IRoQqgkXIHgkFeXwwLwyjEMU.jpg
  fanart: https://image.tmdb.org/t/p/w500/56v2KjBlU4XaOv9rVYEQypROD7P.jpg
  genres:
    - Drame
    - Mystère
    - Science-Fiction & Fantastique
  rating: 8.6
  studio: Netflix
  episode: 'Chapter One: The Hellfire Club'
  number: S04E01
  release: $day, $date $time
  airdate: '2022-05-27T07:00:00Z'

unit_of_measurement: items
icon: mdi:calendar
friendly_name: Trakt Upcoming Premieres
```

But the recommandation sensor are not compatible, for example (defaults are missing):
- sensor.trakt_recommendation_shows
```yaml
data: 
- title: Breaking Bad
  fanart: https://image.tmdb.org/t/p/w500/n3u3kgNttY1F5Ixi5bMY9BwZImQ.jpg
  genres:
    - Drame
  rating: 8.8
  studio: AMC
- title: Game of Thrones
  fanart: https://image.tmdb.org/t/p/w500/suopoADq0k8YZr4dQXcU6pToj6s.jpg
  genres:
    - Science-Fiction & Fantastique
    - Drame
    - Action & Adventure
  rating: 8.4
  studio: HBO
- title: The Mandalorian
  fanart: https://image.tmdb.org/t/p/w500/9ijMGlJKqcslswWUzTEwScm82Gs.jpg
  genres:
    - Science-Fiction & Fantastique
    - Action & Adventure
    - Drame
  rating: 8.5
  studio: Disney+

unit_of_measurement: shows
icon: mdi:movie
friendly_name: Trakt Recommendation Shows
```

It would be nice to have recommandation sensors compatible.

Thanks,

Thomas

**Comment by dylandoamaral** [comment]
It totally should be compatible, I will fix that !

**Comment by thomasgermain** [comment]
I can't get it to work :confused: 

I can see there is now a first item at the beginning of the list for sensor.trakt_recommendation_movies:
```yaml
data: 
- title_default: $title
  line1_default: $episode
  line2_default: $release
  line3_default: $rating - $runtime
  line4_default: $number - $studio
  icon: mdi:arrow-down-bold
- title: Deadpool
  poster: https://image.tmdb.org/t/p/w500/z5VjcCEioj2c2dvxmoqBW0Rj8Xj.jpg
  fanart: https://image.tmdb.org/t/p/w500/en971MEXui9diirXlogOrPKmsEn.jpg
  genres:
    - Action
    - Aventure
    - Comédie
  rating: 7.6
  studio: 20th Century Fox
  runtime: 109
[...]
```

But for for movie it uses the same defaults as shows, but apparently `$episode` and `$number` are only available for shows.

Anyway, I manually modified (through dev tool) attributes like the following, but it still doesn't work:

```yaml
data:
  - title_default: $title
    line1_default: $empty
    line2_default: $empty
    line3_default: $empty
    line4_default: $empty
    icon: mdi:arrow-down-bold
  - title: Deadpool
    poster: https://image.tmdb.org/t/p/w500/z5VjcCEioj2c2dvxmoqBW0Rj8Xj.jpg
    fanart: https://image.tmdb.org/t/p/w500/en971MEXui9diirXlogOrPKmsEn.jpg
    genres:
      - Action
      - Aventure
      - Comédie
    rating: 7.6
    studio: 20th Century Fox
    runtime: 109
[...]
``` 

I also tested with sensor.trakt_recommendation_shows sensor, but same result.

I have no javascript error coming from the custom:upcoming-media-card :confused:
