### ISSUE TITLE
No sensors has been created #2

### ISSUE THREAD

**Issue by rzechu** [dylandoamaral/trakt-integration#60]
Any ideas about missing (not added) sensors or upcoming-media-card configuration?
No info about movies only upcoming show

> Got only 1 default entity (reinstalled trakt integration) 
![image](https://user-images.githubusercontent.com/45091660/211754512-3d3e9008-3282-44f9-b0ed-bcd7d7012479.png)

![image](https://user-images.githubusercontent.com/45091660/211540589-0156936c-394b-4220-84dd-5d03c1c4e8e4.png)
> 
> ![image](https://user-images.githubusercontent.com/45091660/211540551-25021155-8ed0-4638-9086-2e0c91995ec7.png)
> 
> Got working only 1 entity and 1 card
> 
> ```
> resources:
>   - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js?v=0.1.1
>     type: js
> type: custom:upcoming-media-card
> entity: sensor.trakt_upcoming_calendar
> title: Upcoming Episodes
> image_style: fanart
> hide_empty: true
> title_text: $title
> line1_text: $episode
> line2_text: $number
> line3_text: $day, $date $time
> line4_text: $empty
> max: 10
> ```
> 
> ![image](https://user-images.githubusercontent.com/45091660/211540819-cac33d8e-36d1-49e6-bfbb-e5b83e20edef.png)
> 
> My configuration.yaml
> 
> ```
> trakt_tv:
>   language: en
>   timezone: Europe/Paris # Prefered timezone #added this but no difference
>   sensors:
>     upcoming:
>       show:
>         days_to_fetch: 30
>         max_medias: 10
>       movie:
>         days_to_fetch: 45
>         max_medias: 5
>     recommendation:
>       show:
>         max_medias: 3
>       movie:
>         max_medias: 3
> ```
![image](https://user-images.githubusercontent.com/45091660/211755427-c7d68a34-f66f-49ba-b762-d7a3b0f691bc.png)

> 
> Cant add upcoming for movies and I dont see any other sensors even after restart ( show / movie / recommendation etc)
![image](https://user-images.githubusercontent.com/45091660/211754312-7c5ff32f-1cdb-4f94-81a9-463d2c66ca5c.png)

> From documentation
> > There are five sensors available under the sensors > upcoming array:
> > show for TV Shows (actually, episodes). Creates sensor.trakt_upcoming_shows
> > new_show for New Shows (series premiers). Creates sensor.trakt_upcoming_new_shows

**Comment by dylandoamaral** [comment]
I tried a new release I am not very confident but maybe it will help.

**Comment by rzechu** [comment]
@dylandoamaral thank you but I am afraid - nothing changed
![image](https://user-images.githubusercontent.com/45091660/211925565-27f8c48c-b1d6-4a3c-9005-df02faa2c22c.png)

I resolved issue but not sure what helped
1. edited my configuration.yaml  and replaced my trakt_tv config with default one:
```
trakt_tv:
  language: en # Prefered language for movie/show title
  timezone: Europe/Paris # Prefered timezone
  sensors:
    upcoming:
      show:
        days_to_fetch: 90 # How many days in the future you want to fetch
        max_medias: 3 # How many medias you want to fetch
      new_show:
        days_to_fetch: 90
        max_medias: 3
      premiere:
        days_to_fetch: 90
        max_medias: 3
      movie:
        days_to_fetch: 90
        max_medias: 3
      dvd:
        days_to_fetch: 90
        max_medias: 3
    next_to_watch:
      all:
        max_medias: 40
        exclude:
          - veep
          - the-original
          - friends
      only_aired:
        max_medias: 40
        exclude:
          - veep
          - the-original
          - friends
      only_upcoming:
        max_medias: 40      
```
3. put above mentioned section almost at top of my configuration file

after restart new entities appeared 
![image](https://user-images.githubusercontent.com/45091660/211926500-3640a981-48e1-4dc7-bc07-f115d3b1e5c8.png)


anyway thank you for help and great plugin
