### ISSUE TITLE
Trakt List Sensor

### ISSUE THREAD

**Issue by bryan-stewart** [dylandoamaral/trakt-integration#74]
I would love to be able to pull movies/shows from a specified trakt list

API endpoint: https://api.trakt.tv/lists/{id}/items/{type}

It would also be nice to have a sort feature

Something like:

```
sensors:
  lists:
    <custom list name for entity>:
      id: <list id>
      type: 'movies' or 'show' (optional)
      sort_by: 'rank' or 'added' (optional)
      sort_order: 'asc' or 'desc' (optional)
```
