### ISSUE TITLE
Hidden shows showing up in 'next to watch' sensor

### ISSUE THREAD

**Issue by Lackmake** [dylandoamaral/trakt-integration#95]
I just added your integration and configured it successfully, thanks for the work. 
However the sensor i setup behaves differently than i expected.
In my configuration i wrote exactly this:
```
trakt_tv:
  language: de # Prefered language for movie/show title
  timezone: Europe/Berlin # Prefered timezone
  sensors:
    next_to_watch:
      only_aired:
        max_medias: 5
        exclude:
          - hidden
  ```

My goal was to replicate the list trakt.tv is showing on my [dashboard](https://trakt.tv/dashboard), which are the shows i am currently watching with their respective first unwatched/next-up episode for me.
I have many shows hidden on trakt.tv which do not show up on the next-up section on trakt, but do show up in the sensor unfortunately.

You even mentioned the trakt-hide function in the description thats why i thought it would work like this:

> You can also use the Trakt.tv "hidden" function to hide a show from [your calendar](https://trakt.tv/calendars/my/shows) or the [progress page](https://trakt.tv/users/%3Cusername%3E/progress)

Did i misunderstand, misconfigured or is this not working as expected?

**Comment by dylandoamaral** [comment]
This feature was made by @Anrolosia maybe he can gives you more information !

**Comment by Anrolosia** [comment]
Hello there! Not sure there is a bug here, because first the configuration you provided is not correct, check the documentation, exclude is supposed to be an array of slugs
![image](https://github.com/dylandoamaral/trakt-integration/assets/1843399/4205e6a4-2f6e-434f-a1b6-c5563e97091e)

Also, every show you have listed in https://trakt.tv/settings/hidden shouldn't appear with this module, there is a fetch of that list (but there is also some caching, maybe this is why)
https://github.com/dylandoamaral/trakt-integration/blob/main/custom_components/trakt_tv/apis/trakt.py#L142-L162

**Comment by saragrigolin** [comment]
Hello,
I'm having the same issue, that means the hidden shows that are listed in https://trakt.tv/settings/hidden are showing up in "next to watch" sensor.
In the screenshot below, you can see my hidden shows on Trakt, and the next to watch shows of the Home Assistant sensor. For example, Lioness and XFactor (IT) should not be there.
I already tried this syntax, even if the documentation says that the hidden shows should not be visible by default, but with no success.
```
sensors:
   next_to_watch:
     only_aired:
       max_medias: 5
       exclude:
          - hidden
```

I also tried to restart HA several times, and clear the cache etc. What can I do?

<img width="968" alt="Image" src="https://github.com/user-attachments/assets/835e093d-a0af-45eb-a256-6c1731165fdf" />

<img width="541" alt="Image" src="https://github.com/user-attachments/assets/89e060db-3688-4237-90e8-396061a1b658" />
